# Generated by Django 5.0.2 on 2024-02-06 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorieVoyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='voyage_images/')),
                ('titre_categ', models.CharField(blank=True, max_length=50)),
                ('description_categ', models.CharField(blank=True, max_length=300)),
                ('description_courte', models.CharField(blank=True, max_length=100, null=True)),
                ('reduction_percent', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('special_request', models.TextField(blank=True)),
                ('number_of_persons', models.PositiveIntegerField()),
                ('baggage_weight_kg', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='voyage_images/')),
                ('ville_origine', models.CharField(blank=True, max_length=50)),
                ('ville_destination', models.CharField(blank=True, max_length=50)),
                ('date_aller', models.DateField(blank=True, null=True)),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('prix', models.IntegerField(default=0)),
                ('nombre_personnes', models.IntegerField(default=1)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('categorie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp.categorievoyage')),
            ],
        ),
    ]
