# Generated by Django 5.0.2 on 2024-02-06 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
